// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Platform Team"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/agent-ops/{id}": {
            "get": {
                "description": "Returns the ledger row (id, opType, status, detail, message) — the polling fallback for environments where SSE is impractical.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent-ops"
                ],
                "summary": "Get one agent op",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent op ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            }
        },
        "/agent-ops/{id}/stream": {
            "get": {
                "description": "Replays persisted log chunks, then pushes live status/log events; closes after a terminal status (succeeded|failed).",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "agent-ops"
                ],
                "summary": "Stream one agent op's output and status (SSE)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent op ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "text/event-stream",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            }
        },
        "/environments/{id}/exec": {
            "post": {
                "description": "Validates the request and records an agent_ops entry (queued); execution is performed by the Runner / direct-connect executor, not the hub (no client-go).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "environments"
                ],
                "summary": "Queue a direct-exec operation on the environment's target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Environment ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "command or script (at least one)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_environment_service.ExecRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            }
        },
        "/pipelines/{id}/versions": {
            "get": {
                "description": "Returns the append-only snapshot history (newest first): version number, author, stage/task counts, and whether the body differs from the previous version. Bodies are omitted — fetch one with GET /pipelines/:id/versions/:version.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipelines"
                ],
                "summary": "List a pipeline's definition versions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "max versions to return (default 50, max 200)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            }
        },
        "/pipelines/{id}/versions/{version}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipelines"
                ],
                "summary": "Get one pipeline definition version (full snapshot body)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Version number",
                        "name": "version",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            }
        },
        "/pipelines/{id}/versions/{version}/diff": {
            "get": {
                "description": "Returns the stage/task level differences from ?against=\u003cn\u003e to :version. Directional: added/removed swap if :version is the older one.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipelines"
                ],
                "summary": "Diff two versions of a pipeline definition",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Target version number",
                        "name": "version",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Baseline version number",
                        "name": "against",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            }
        },
        "/pipelines/{id}/versions/{version}/rollback": {
            "post": {
                "description": "Re-materializes the version's stages and task templates and records the result as a new version. Structure only — pipeline metadata (name/kind/description) is left alone. History is append-only: no version rows are rewritten or deleted.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipelines"
                ],
                "summary": "Roll a pipeline's structure back to a past version",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Version number to restore",
                        "name": "version",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            }
        },
        "/pipelines/{pipelineId}/runs": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "List pipeline runs for a pipeline",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline ID (UUID)",
                        "name": "pipelineId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size (default 20, max 100)",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            },
            "post": {
                "description": "Assembles a PipelineRunSpec from the pipeline's current stages/tasks and dispatches it to a target Runner. Set targetIds to fan the same trigger out to multiple environments (one independent run per target); ignored when targetId is set.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Trigger a pipeline run",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline ID (UUID)",
                        "name": "pipelineId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Trigger request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_run_models.TriggerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            }
        },
        "/pipelines/{pipelineId}/runs/{runId}/tasks/{taskName}/decision": {
            "post": {
                "description": "Relays an approver's decision to the Runner via the gateway. Approver defaults to the current user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Submit an approval decision for a paused Approval task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline ID (UUID)",
                        "name": "pipelineId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pipeline Run ID (UUID)",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Task name awaiting approval",
                        "name": "taskName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Approval decision",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_run_handler.ApprovalDecisionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            }
        },
        "/runs": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "List pipeline runs across all pipelines (Run Center)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "filter by phase, e.g. Failed / Running / Succeeded",
                        "name": "phase",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size (default 20, max 100)",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            }
        },
        "/runs/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Get a pipeline run by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline Run ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            }
        },
        "/runs/{id}/cancel": {
            "post": {
                "description": "Asks the Runner owning the run to stop it: mark the PipelineRun Cancelled and tear down its in-flight TaskRuns. Only a Pending / Running / WaitingApproval run can be cancelled; a finished run returns 409. The new phase is recorded when the Runner streams its status update back.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Cancel a running pipeline run",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline Run ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            }
        },
        "/runs/{id}/progress": {
            "get": {
                "description": "Lightweight status endpoint for high-frequency console polling; returns the run phase and per-task status rows, not the full pipeline definition.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Get a pipeline run's live progress (phase + per-task status)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline Run ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            }
        },
        "/runs/{id}/redispatch": {
            "post": {
                "description": "Re-enqueues a fresh dispatch job carrying the last payload for a run whose delivery is stuck (failed/dead) or unconfirmed. Succeeds even if the Runner is offline; the job is delivered on reconnect or by the sweeper. A run stuck in Failed is reset to Pending.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Re-deliver a pipeline run's spec to its target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline Run ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            }
        },
        "/runs/{id}/stage-progress": {
            "get": {
                "description": "Aggregated stage rows (name/sequence/executionMode/status/done/total) derived on read from the run's TaskRuns; feeds console §7.6 stage cards.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Per-stage progress of a pipeline run",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline Run ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            }
        },
        "/runs/{id}/tasks": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "List tasks of a pipeline run",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline Run ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            }
        },
        "/runs/{id}/tasks/{name}/log": {
            "get": {
                "description": "Returns the ordered log chunks the hub persisted as a Runner streamed them over MessageLogChunk. Use the :name path param for a specific DAG task, or the /runs/:id/log variant for run-level output. Chunks are served in emission order.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Get a task's (or run-level) streamed logs for a pipeline run",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline Run ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Task name; the run-level log uses the bucket __run__",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size (default 20, max 100)",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            }
        },
        "/runs/{id}/tasks/{name}/rerun": {
            "post": {
                "description": "Asks the Runner owning the run to reset one task (and, on the Runner, every downstream task that depends on it) so the DAG picks it up again — without re-dispatching the whole run.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Re-run a single task of a pipeline run",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline Run ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Task name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            }
        },
        "/runs/{id}/tasks/{name}/rollout": {
            "post": {
                "description": "Relays the operator command to the Runner via the gateway; the resulting phase change streams back via status updates.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Send a pause/promote/rollback command to a Release task's Rollout",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pipeline Run ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Release task name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Rollout control command",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_run_handler.RolloutControlRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            }
        },
        "/targets/{id}/agent-ops": {
            "get": {
                "description": "Paged ledger listing (newest first) — the console's per-target operation history.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent-ops"
                ],
                "summary": "List agent ops of a target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            }
        },
        "/targets/{id}/install": {
            "post": {
                "description": "Records an agent_ops entry (queued) carrying the runner version from the package-versions matrix; execution is the Runner's job (§9.9).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "targets"
                ],
                "summary": "Queue a runner install on the target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            }
        },
        "/targets/{id}/upgrade": {
            "post": {
                "description": "Records an agent_ops entry (queued) carrying the runner version from the package-versions matrix; execution is the Runner's job (§9.9).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "targets"
                ],
                "summary": "Queue a runner upgrade on the target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_rouroumaibing_software-distribution-platform-hub_internal_common.Envelope": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "errorCode": {
                    "type": "string"
                },
                "reasons": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_rouroumaibing_software-distribution-platform-hub_internal_environment_service.ExecRequest": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string"
                },
                "script": {
                    "type": "string"
                }
            }
        },
        "github_com_rouroumaibing_software-distribution-platform-hub_internal_run_models.TriggerRequest": {
            "type": "object",
            "properties": {
                "commitSha": {
                    "description": "CommitSHA records the resolved commit for audit display.",
                    "type": "string"
                },
                "params": {
                    "description": "Params are substituted into task command/args/env by the runner.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1alpha1.Param"
                    }
                },
                "repoPath": {
                    "type": "string"
                },
                "repoRef": {
                    "type": "string"
                },
                "repoUrl": {
                    "description": "RepoURL/RepoRef/RepoPath describe the source checkout for script tasks.\nThe hub resolves Ref to a concrete commit SHA at trigger time.",
                    "type": "string"
                },
                "targetId": {
                    "description": "TargetID overrides target selection. If nil/empty, the hub picks the\nfirst online target. Ignored when TargetIDs is set.",
                    "type": "string"
                },
                "targetIds": {
                    "description": "TargetIDs fans the trigger out to multiple environments: one independent\nPipelineRun is created per listed target (each keeps the 1:1 run↔target\ninvariant). Targets only need to EXIST, not be online — the durable\ndispatch queue delivers each run once its Runner reconnects.\nWhen set, TargetID is ignored.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "targetNamespace": {
                    "description": "TargetNamespace is the K8s namespace the runner creates Jobs in.\nDefaults to \"sdp-run\" when empty.",
                    "type": "string"
                },
                "triggeredBy": {
                    "description": "TriggeredBy is the hub-side user/system identity starting the run.",
                    "type": "string"
                }
            }
        },
        "internal_run_handler.ApprovalDecisionRequest": {
            "type": "object",
            "properties": {
                "approved": {
                    "description": "Approved is true to sign off, false to reject.",
                    "type": "boolean"
                },
                "approver": {
                    "description": "Approver optionally overrides the identity recorded on the Runner;\ndefaults to the authenticated user (or the dev user in dev mode).",
                    "type": "string"
                },
                "reason": {
                    "description": "Reason is free text for the audit trail (stored by the Runner).",
                    "type": "string"
                }
            }
        },
        "internal_run_handler.RolloutControlRequest": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "Action is one of pause | promote | rollback.",
                    "type": "string"
                },
                "operator": {
                    "description": "Operator optionally overrides the identity recorded on the Runner;\ndefaults to the authenticated user (or the dev user in dev mode).",
                    "type": "string"
                }
            }
        },
        "v1alpha1.Param": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Software Distribution Platform Hub API",
	Description:      "Control plane API for the K8s software distribution platform: orgs, catalogs, components, pipelines, runs, targets and permissions, plus a Runner WebSocket gateway.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
